'use client';
import { Button } from '@/components/ui/button';
import { ArrowRight, PlayCircle, Bot, BarChart, Clock, Search, Mail, Layers, Trophy, FileText, BarChart2, Zap, Sparkles } from 'lucide-react';
import Link from 'next/link';
import React, { Suspense } from 'react';
import { motion } from 'framer-motion';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import Image from 'next/image';

const MotionCard = ({ children, delay = 0, className }: { children: React.ReactNode, delay?: number, className?: string }) => (
    <motion.div
        className={className}
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.2 }}
        transition={{ delay, duration: 0.5, ease: "easeOut" }}
    >
        {children}
    </motion.div>
);

const statCards = [
    { icon: <Trophy className="text-primary"/>, value: "1M+", title: "AI-Powered Posts", description: "Generated by our smart engine" },
    { icon: <FileText className="text-primary"/>, value: "10k+", title: "Hours Saved", description: "Across all our happy clients" },
    { icon: <BarChart2 className="text-primary"/>, value: "45%", title: "Higher Engagement", description: "On average compared to manual posts" },
    { icon: <Zap className="text-primary"/>, value: "24/7", title: "Automation", description: "Your social media never sleeps" },
]

export default function RootPage() {
  return (
    <div className="w-full font-sans bg-background text-foreground overflow-x-hidden">
        {/* Hero Section */}
        <div className="relative overflow-hidden bg-background">
             <div className="container mx-auto px-6 py-24 md:py-32 grid lg:grid-cols-2 gap-12 items-center">
                <MotionCard>
                    <div className="inline-flex items-center bg-blue-100 text-primary font-semibold px-4 py-1.5 rounded-full text-sm mb-4">
                        <Sparkles className="w-4 h-4 mr-2"/>
                        Working for your success
                    </div>
                    <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter leading-tight">
                        Automate Your <span className="text-primary">Social Media,</span> Elevate Your Brand.
                    </h1>
                    <p className="mt-6 max-w-xl text-lg text-muted-foreground">
                        OmniPost is your intelligent, all-in-one platform to create, schedule, and analyze your social media presence, freeing you to focus on growth.
                    </p>
                    <div className="mt-8 flex items-center gap-4">
                         <Button size="lg" asChild className="shadow-lg hover:shadow-primary/30 transition-shadow">
                            <Link href="/signup">
                                Get Started <ArrowRight className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                         <Button size="lg" variant="ghost" asChild>
                            <Link href="#services">
                                <PlayCircle className="mr-2 h-5 w-5" />
                                Watch Demo
                            </Link>
                        </Button>
                    </div>
                </MotionCard>
                 <MotionCard delay={0.1} className="hidden lg:block relative">
                    <Image 
                        src="https://picsum.photos/seed/collab/800/600"
                        alt="Team collaborating on social media analytics"
                        width={800}
                        height={600}
                        className="rounded-2xl shadow-2xl"
                        data-ai-hint="team collaborating"
                    />
                     <div className="absolute -bottom-8 right-8 bg-white/70 backdrop-blur-lg p-4 rounded-xl shadow-xl border w-72">
                        <div className="flex items-center mb-2">
                           <div className="flex -space-x-2">
                            <img className="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://picsum.photos/seed/avatar1/40/40" alt="User 1"/>
                            <img className="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://picsum.photos/seed/avatar2/40/40" alt="User 2"/>
                            <img className="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://picsum.photos/seed/avatar3/40/40" alt="User 3"/>
                             <div className="h-8 w-8 rounded-full ring-2 ring-white bg-gray-200 flex items-center justify-center text-xs font-bold text-gray-600">+12k</div>
                           </div>
                        </div>
                        <p className="text-xs text-muted-foreground font-medium">
                            <span className="font-bold text-foreground">12,000+ happy clients</span> are automating their social media presence with OmniPost AI.
                        </p>
                    </div>
                </MotionCard>
            </div>
        </div>
        
        {/* Stats Section */}
        <div className="py-20 md:py-24">
            <div className="container mx-auto px-6">
                <div className="bg-white/50 backdrop-blur-lg rounded-2xl shadow-xl border p-8 grid grid-cols-2 lg:grid-cols-4 gap-8">
                    {statCards.map((card, index) => (
                        <MotionCard key={card.title} delay={index * 0.1}>
                           <div className="text-center lg:text-left flex flex-col lg:flex-row items-center gap-4">
                             <div className="p-4 bg-blue-100 rounded-lg">
                                {card.icon}
                             </div>
                             <div>
                                <p className="text-3xl font-bold text-foreground">{card.value}</p>
                                <p className="text-sm font-semibold text-muted-foreground mt-1">{card.title}</p>
                             </div>
                           </div>
                        </MotionCard>
                    ))}
                </div>
            </div>
        </div>

        {/* Placeholder sections for future content */}
        <div id="about" className="py-20 md:py-28 bg-secondary/30">
            <div className="container mx-auto px-4 text-center">
                <MotionCard>
                     <h2 className="text-3xl md:text-4xl font-bold">About OmniPost AI</h2>
                    <p className="mt-4 text-muted-foreground max-w-2xl mx-auto">This is where you can talk about your company's mission and vision. More content coming soon!</p>
                </MotionCard>
            </div>
        </div>

        <div id="features" className="py-20 md:py-28">
            <div className="container mx-auto px-4 text-center">
                <MotionCard>
                     <h2 className="text-3xl md:text-4xl font-bold">Features That Set Us Apart</h2>
                    <p className="mt-4 text-muted-foreground max-w-2xl mx-auto">This section will detail all the amazing features of your platform. More content coming soon!</p>
                </MotionCard>
            </div>
        </div>
        
        {/* CTA Section */}
        <div className="py-20 md:py-28 bg-secondary/30">
            <div className="container mx-auto px-4 text-center">
                 <MotionCard>
                    <h2 className="text-3xl md:text-4xl font-bold">Ready to Elevate Your Digital Strategy?</h2>
                    <p className="mt-3 text-muted-foreground max-w-xl mx-auto">Let's make things happen. Join OmniPost today and start automating your success.</p>
                    <div className="mt-8">
                        <Button size="lg" asChild className="shadow-lg shadow-primary/20 transition-all">
                             <Link href="/signup">
                                Start Your Free Trial <ArrowRight className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                    </div>
                </MotionCard>
            </div>
        </div>
    </div>
  );
}
