'use client';
import { Button } from '@/components/ui/button';
import { ArrowRight, PlayCircle, Bot, BarChart, Clock, Search, Mail, Layers, Trophy, FileText, BarChart2, Zap, Sparkles } from 'lucide-react';
import Link from 'next/link';
import React, { Suspense } from 'react';
import { motion } from 'framer-motion';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import Image from 'next/image';

const MotionCard = ({ children, delay = 0, className }: { children: React.ReactNode, delay?: number, className?: string }) => (
    <motion.div
        className={className}
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, amount: 0.2 }}
        transition={{ delay, duration: 0.5, ease: "easeOut" }}
    >
        {children}
    </motion.div>
);

const statCards = [
    { icon: <Trophy className="text-primary"/>, value: "1M+", title: "AI-Powered Posts", description: "Generated by our smart engine" },
    { icon: <FileText className="text-primary"/>, value: "10k+", title: "Hours Saved", description: "Across all our happy clients" },
    { icon: <BarChart2 className="text-primary"/>, value: "45%", title: "Higher Engagement", description: "On average compared to manual posts" },
    { icon: <Zap className="text-primary"/>, value: "24/7", title: "Automation", description: "Your social media never sleeps" },
]

export default function RootPage() {
  return (
    <div className="w-full font-sans bg-background text-foreground overflow-x-hidden">
        {/* Hero Section */}
        <div className="relative overflow-hidden bg-background">
             <div className="container mx-auto px-6 py-24 md:py-32 grid lg:grid-cols-2 gap-12 items-center">
                <MotionCard>
                    <div className="inline-flex items-center bg-primary/10 text-primary font-semibold px-4 py-1.5 rounded-full text-sm mb-4">
                        <Sparkles className="w-4 h-4 mr-2"/>
                        #1 AI Social Media Tool
                    </div>
                    <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter leading-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">
                        Automate The Manual Work, Not The Results.
                    </h1>
                    <p className="mt-6 max-w-xl text-lg text-muted-foreground">
                        TrendXoda is your intelligent, all-in-one platform to create, schedule, and analyze your social media presence, freeing you to focus on growth.
                    </p>
                    <div className="mt-8 flex items-center gap-4">
                         <Button size="lg" asChild className="shadow-lg hover:shadow-primary/30 transition-shadow">
                            <Link href="/signup">
                                Get Started For Free <ArrowRight className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                    </div>
                </MotionCard>
                 <MotionCard delay={0.1} className="hidden lg:block relative h-[450px]">
                    <Image 
                        src="https://picsum.photos/seed/dashboard/800/600"
                        alt="Dashboard preview of TrendXoda"
                        width={800}
                        height={600}
                        className="rounded-2xl shadow-2xl absolute top-0 left-0 w-full h-full object-cover"
                        data-ai-hint="dashboard ui"
                    />
                </MotionCard>
            </div>
        </div>
        
        {/* How It Works Section */}
        <div id="how-it-works" className="py-20 md:py-28 bg-secondary/30">
            <div className="container mx-auto px-4">
                <MotionCard className="text-center mb-16">
                     <h2 className="text-3xl md:text-4xl font-bold">How It Works</h2>
                    <p className="mt-4 text-muted-foreground max-w-2xl mx-auto">Three simple steps to automate your social media and supercharge your growth with TrendXoda.</p>
                </MotionCard>

                <div className="space-y-20">
                    {/* Step 1 */}
                    <div className="grid md:grid-cols-2 gap-12 items-center">
                        <MotionCard>
                            <div className="mb-4">
                                <span className="inline-block px-4 py-2 bg-primary/10 text-primary font-bold rounded-full">Step 1</span>
                            </div>
                            <h3 className="text-3xl font-bold mb-4">Create with AI</h3>
                            <p className="text-muted-foreground text-lg">Generate engaging captions, viral video scripts, and brilliant campaign ideas in seconds. Our AI is trained to understand your brand and create content that converts.</p>
                        </MotionCard>
                        <MotionCard delay={0.2}>
                            <Image src="https://picsum.photos/seed/ai-creation/800/600" alt="AI content creation" width={800} height={600} className="rounded-2xl shadow-xl" data-ai-hint="ai content" />
                        </MotionCard>
                    </div>

                    {/* Step 2 */}
                    <div className="grid md:grid-cols-2 gap-12 items-center">
                         <MotionCard delay={0.2} className="md:order-last">
                             <div className="mb-4">
                                <span className="inline-block px-4 py-2 bg-primary/10 text-primary font-bold rounded-full">Step 2</span>
                            </div>
                            <h3 className="text-3xl font-bold mb-4">Schedule with Ease</h3>
                            <p className="text-muted-foreground text-lg">Plan your content calendar across all your platforms from one simple interface. Our AI can even suggest the best time to post for maximum engagement.</p>
                        </MotionCard>
                        <MotionCard>
                            <Image src="https://picsum.photos/seed/scheduling/800/600" alt="Social media scheduling calendar" width={800} height={600} className="rounded-2xl shadow-xl" data-ai-hint="calendar schedule" />
                        </MotionCard>
                    </div>

                     {/* Step 3 */}
                    <div className="grid md:grid-cols-2 gap-12 items-center">
                        <MotionCard>
                             <div className="mb-4">
                                <span className="inline-block px-4 py-2 bg-primary/10 text-primary font-bold rounded-full">Step 3</span>
                            </div>
                            <h3 className="text-3xl font-bold mb-4">Track Performance</h3>
                            <p className="text-muted-foreground text-lg">Get deep insights into what's working. Track your growth, engagement, and reach with our beautiful and easy-to-understand analytics dashboard.</p>
                        </MotionCard>
                        <MotionCard delay={0.2}>
                            <Image src="https://picsum.photos/seed/analytics-graph/800/600" alt="Analytics dashboard with graphs" width={800} height={600} className="rounded-2xl shadow-xl" data-ai-hint="analytics graph" />
                        </MotionCard>
                    </div>
                </div>
            </div>
        </div>

        {/* CTA Section */}
        <div className="py-20 md:py-28">
            <div className="container mx-auto px-4 text-center">
                 <MotionCard>
                    <h2 className="text-3xl md:text-4xl font-bold">Ready to Elevate Your Digital Strategy?</h2>
                    <p className="mt-3 text-muted-foreground max-w-xl mx-auto">Let's make things happen. Join TrendXoda today and start automating your success.</p>
                    <div className="mt-8">
                        <Button size="lg" asChild className="shadow-lg shadow-primary/20 transition-all">
                             <Link href="/signup">
                                Start Your Free Trial <ArrowRight className="ml-2 h-5 w-5" />
                            </Link>
                        </Button>
                    </div>
                </MotionCard>
            </div>
        </div>
    </div>
  );
}
